use diesel::prelude::*;

use crate::schema::market_candidates;

#[derive(Debug, Clone, Queryable, Selectable)]
#[diesel(table_name = market_candidates)]
pub struct MarketCandidateRow {
    pub candidate_id: i32,
    pub market_id: Vec<u8>,
    pub oracle_public_key: Vec<u8>,
    pub collateral_asset_id: Vec<u8>,
    pub yes_token_asset: Vec<u8>,
    pub no_token_asset: Vec<u8>,
    pub yes_reissuance_token: Vec<u8>,
    pub no_reissuance_token: Vec<u8>,
    pub collateral_per_token: i64,
    pub expiry_time: i32,
    pub cmr: Vec<u8>,
    pub dormant_yes_rt_spk: Vec<u8>,
    pub dormant_no_rt_spk: Vec<u8>,
    pub unresolved_yes_rt_spk: Vec<u8>,
    pub unresolved_no_rt_spk: Vec<u8>,
    pub unresolved_collateral_spk: Vec<u8>,
    pub resolved_yes_collateral_spk: Vec<u8>,
    pub resolved_no_collateral_spk: Vec<u8>,
    pub expired_collateral_spk: Vec<u8>,
    pub yes_issuance_entropy: Option<Vec<u8>>,
    pub no_issuance_entropy: Option<Vec<u8>>,
    pub yes_issuance_blinding_nonce: Option<Vec<u8>>,
    pub no_issuance_blinding_nonce: Option<Vec<u8>>,
    pub question: Option<String>,
    pub description: Option<String>,
    pub category: Option<String>,
    pub resolution_source: Option<String>,
    pub creator_pubkey: Option<Vec<u8>>,
    pub creation_txid: String,
    pub yes_dormant_asset_blinding_factor: Vec<u8>,
    pub yes_dormant_value_blinding_factor: Vec<u8>,
    pub no_dormant_asset_blinding_factor: Vec<u8>,
    pub no_dormant_value_blinding_factor: Vec<u8>,
    pub creation_tx: Vec<u8>,
    pub nevent: Option<String>,
    pub nostr_event_id: Option<String>,
    pub nostr_event_json: Option<String>,
    pub first_seen_at: String,
    pub last_seen_at: String,
    pub expires_at: Option<String>,
    pub promoted_at: Option<String>,
    pub promotion_height: Option<i32>,
    pub promotion_block_hash: Option<Vec<u8>>,
}

#[derive(Debug, Clone, Insertable)]
#[diesel(table_name = market_candidates)]
pub struct NewMarketCandidateRow {
    pub market_id: Vec<u8>,
    pub oracle_public_key: Vec<u8>,
    pub collateral_asset_id: Vec<u8>,
    pub yes_token_asset: Vec<u8>,
    pub no_token_asset: Vec<u8>,
    pub yes_reissuance_token: Vec<u8>,
    pub no_reissuance_token: Vec<u8>,
    pub collateral_per_token: i64,
    pub expiry_time: i32,
    pub cmr: Vec<u8>,
    pub dormant_yes_rt_spk: Vec<u8>,
    pub dormant_no_rt_spk: Vec<u8>,
    pub unresolved_yes_rt_spk: Vec<u8>,
    pub unresolved_no_rt_spk: Vec<u8>,
    pub unresolved_collateral_spk: Vec<u8>,
    pub resolved_yes_collateral_spk: Vec<u8>,
    pub resolved_no_collateral_spk: Vec<u8>,
    pub expired_collateral_spk: Vec<u8>,
    pub question: Option<String>,
    pub description: Option<String>,
    pub category: Option<String>,
    pub resolution_source: Option<String>,
    pub creator_pubkey: Option<Vec<u8>>,
    pub creation_txid: String,
    pub yes_dormant_asset_blinding_factor: Vec<u8>,
    pub yes_dormant_value_blinding_factor: Vec<u8>,
    pub no_dormant_asset_blinding_factor: Vec<u8>,
    pub no_dormant_value_blinding_factor: Vec<u8>,
    pub creation_tx: Vec<u8>,
    pub nevent: Option<String>,
    pub nostr_event_id: Option<String>,
    pub nostr_event_json: Option<String>,
    pub first_seen_at: String,
    pub last_seen_at: String,
    pub expires_at: Option<String>,
}
