import type { MarketGroup } from "../types";

// Mock current block height ~852,000 (late April 2026).
// US Open starts June 12 → ~7,200 blocks away → expiry 859,200
// NBA Finals start ~June 5 → ~5,760 blocks away → expiry 857,760

export function getMockMarketGroups(): MarketGroup[] {
  return [US_OPEN_2026, NBA_FINALS_2026];
}

const US_OPEN_2026: MarketGroup = {
  id: "group-us-open-2026",
  title: "2026 US Open Golf Winner",
  description:
    "Which golfer will win the 2026 US Open Championship at Oakmont Country Club (June 12–15)?  Each outcome is a binary contract: YES pays 2× collateral if the named player wins, NO pays 2× if they don't.",
  category: "Sports",
  resolutionSource: "PGA TOUR official results · usopen.com",
  expiryHeight: 859_200,
  currentHeight: 852_000,
  totalVolumeBtc: 4.812,
  traderCount: 2_341,
  createdAt: Date.now() - 12 * 24 * 60 * 60 * 1000,
  state: "active",
  cptSats: 10_000,
  outcomes: [
    {
      id: "ou-scottie",
      name: "Scottie Scheffler",
      yesPrice: 0.21,
      change24h: 0.012,
      volumeBtc: 0.94,
      traderCount: 412,
    },
    {
      id: "ou-rory",
      name: "Rory McIlroy",
      yesPrice: 0.15,
      change24h: 0.031,
      volumeBtc: 0.81,
      traderCount: 387,
    },
    {
      id: "ou-xander",
      name: "Xander Schauffele",
      yesPrice: 0.11,
      change24h: -0.008,
      volumeBtc: 0.52,
      traderCount: 261,
    },
    {
      id: "ou-collin",
      name: "Collin Morikawa",
      yesPrice: 0.09,
      change24h: 0.005,
      volumeBtc: 0.43,
      traderCount: 198,
    },
    {
      id: "ou-ludvig",
      name: "Ludvig Åberg",
      yesPrice: 0.08,
      change24h: -0.014,
      volumeBtc: 0.38,
      traderCount: 174,
    },
    {
      id: "ou-viktor",
      name: "Viktor Hovland",
      yesPrice: 0.07,
      change24h: 0.002,
      volumeBtc: 0.31,
      traderCount: 143,
    },
    {
      id: "ou-bryson",
      name: "Bryson DeChambeau",
      yesPrice: 0.06,
      change24h: -0.003,
      volumeBtc: 0.24,
      traderCount: 118,
    },
    {
      id: "ou-cantlay",
      name: "Patrick Cantlay",
      yesPrice: 0.05,
      change24h: 0.001,
      volumeBtc: 0.19,
      traderCount: 92,
    },
    {
      id: "ou-tommy",
      name: "Tommy Fleetwood",
      yesPrice: 0.04,
      change24h: 0.009,
      volumeBtc: 0.15,
      traderCount: 76,
    },
    {
      id: "ou-lowry",
      name: "Shane Lowry",
      yesPrice: 0.04,
      change24h: -0.002,
      volumeBtc: 0.13,
      traderCount: 64,
    },
    {
      id: "ou-homa",
      name: "Max Homa",
      yesPrice: 0.03,
      change24h: 0.004,
      volumeBtc: 0.09,
      traderCount: 47,
    },
    {
      id: "ou-clark",
      name: "Wyndham Clark",
      yesPrice: 0.03,
      change24h: -0.001,
      volumeBtc: 0.08,
      traderCount: 43,
    },
    {
      id: "ou-tony",
      name: "Tony Finau",
      yesPrice: 0.02,
      change24h: 0.0,
      volumeBtc: 0.06,
      traderCount: 31,
    },
    {
      id: "ou-field-golf",
      name: "Field (any other player)",
      yesPrice: 0.02,
      change24h: -0.005,
      volumeBtc: 0.05,
      traderCount: 28,
    },
  ],
};

const NBA_FINALS_2026: MarketGroup = {
  id: "group-nba-finals-2026",
  title: "2026 NBA Championship Winner",
  description:
    "Which team will win the 2026 NBA Championship? The Finals are expected to begin in early June 2026. Each outcome is a binary contract: YES pays 2× collateral if the named team wins, NO pays 2× if they don't.",
  category: "Sports",
  resolutionSource: "NBA.com official results",
  expiryHeight: 857_760,
  currentHeight: 852_000,
  totalVolumeBtc: 6.237,
  traderCount: 3_108,
  createdAt: Date.now() - 28 * 24 * 60 * 60 * 1000,
  state: "active",
  cptSats: 10_000,
  outcomes: [
    {
      id: "ou-celtics",
      name: "Boston Celtics",
      yesPrice: 0.24,
      change24h: -0.018,
      volumeBtc: 1.42,
      traderCount: 681,
    },
    {
      id: "ou-thunder",
      name: "Oklahoma City Thunder",
      yesPrice: 0.21,
      change24h: 0.024,
      volumeBtc: 1.28,
      traderCount: 592,
    },
    {
      id: "ou-cavs",
      name: "Cleveland Cavaliers",
      yesPrice: 0.16,
      change24h: 0.011,
      volumeBtc: 0.87,
      traderCount: 401,
    },
    {
      id: "ou-warriors",
      name: "Golden State Warriors",
      yesPrice: 0.1,
      change24h: -0.007,
      volumeBtc: 0.61,
      traderCount: 298,
    },
    {
      id: "ou-nuggets",
      name: "Denver Nuggets",
      yesPrice: 0.08,
      change24h: 0.003,
      volumeBtc: 0.47,
      traderCount: 221,
    },
    {
      id: "ou-lakers",
      name: "Los Angeles Lakers",
      yesPrice: 0.07,
      change24h: -0.012,
      volumeBtc: 0.43,
      traderCount: 209,
    },
    {
      id: "ou-pacers",
      name: "Indiana Pacers",
      yesPrice: 0.05,
      change24h: 0.006,
      volumeBtc: 0.31,
      traderCount: 148,
    },
    {
      id: "ou-heat",
      name: "Miami Heat",
      yesPrice: 0.04,
      change24h: 0.002,
      volumeBtc: 0.24,
      traderCount: 117,
    },
    {
      id: "ou-knicks",
      name: "New York Knicks",
      yesPrice: 0.03,
      change24h: -0.004,
      volumeBtc: 0.19,
      traderCount: 94,
    },
    {
      id: "ou-bucks",
      name: "Milwaukee Bucks",
      yesPrice: 0.02,
      change24h: 0.001,
      volumeBtc: 0.12,
      traderCount: 58,
    },
  ],
};
