/**
 * Mock market data for screenshots and dev mode.
 * Loaded via "Load Demo Markets" button in Dev settings.
 */
import type { Market } from "./types.ts";

const hex64 = (seed: number): string =>
  Array.from({ length: 64 }, (_, i) =>
    ((seed * (i + 1) * 7 + i * 13) % 16).toString(16),
  ).join("");

export const MOCK_MARKETS: Market[] = [
  {
    id: "mock-1",
    nevent: "nevent1mock1",
    question: "Will Bitcoin exceed $150k by end of 2026?",
    category: "Bitcoin",
    description:
      "Resolves YES if BTC/USD spot price on any major exchange exceeds $150,000 before Jan 1, 2027.",
    resolutionSource: "Coinbase spot price",
    isLive: true,
    state: 1,
    marketId: "mock-market-1",
    oraclePubkey: hex64(1),
    expiryHeight: 900000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(10),
    yesAssetId: hex64(11),
    noAssetId: hex64(12),
    yesReissuanceToken: hex64(13),
    noReissuanceToken: hex64(14),
    creationTxid: hex64(15),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.72,
    change24h: 0.034,
    volumeBtc: 2.45,
    liquidityBtc: 8.12,
    limitOrders: [],
  },
  {
    id: "mock-2",
    nevent: "nevent1mock2",
    question: "Will the US pass a Bitcoin strategic reserve bill in 2026?",
    category: "Politics",
    description:
      "Resolves YES if the US Congress passes legislation establishing a national Bitcoin reserve before Dec 31, 2026.",
    resolutionSource: "Congressional Record",
    isLive: true,
    state: 1,
    marketId: "mock-market-2",
    oraclePubkey: hex64(2),
    expiryHeight: 910000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(20),
    yesAssetId: hex64(21),
    noAssetId: hex64(22),
    yesReissuanceToken: hex64(23),
    noReissuanceToken: hex64(24),
    creationTxid: hex64(25),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.38,
    change24h: -0.052,
    volumeBtc: 5.8,
    liquidityBtc: 14.3,
    limitOrders: [],
  },
  {
    id: "mock-3",
    nevent: "nevent1mock3",
    question: "Will a major hurricane hit Florida before October 2026?",
    category: "Weather",
    description:
      "Resolves YES if a Category 3+ hurricane makes landfall in Florida before Oct 31, 2026.",
    resolutionSource: "National Hurricane Center",
    isLive: true,
    state: 1,
    marketId: "mock-market-3",
    oraclePubkey: hex64(3),
    expiryHeight: 905000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(30),
    yesAssetId: hex64(31),
    noAssetId: hex64(32),
    yesReissuanceToken: hex64(33),
    noReissuanceToken: hex64(34),
    creationTxid: hex64(35),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.61,
    change24h: 0.018,
    volumeBtc: 1.2,
    liquidityBtc: 3.5,
    limitOrders: [],
  },
  {
    id: "mock-4",
    nevent: "nevent1mock4",
    question: "Will the Fed cut rates below 3% by Q4 2026?",
    category: "Macro",
    description:
      "Resolves YES if the Federal Funds Rate target is below 3.00% at any point before Dec 31, 2026.",
    resolutionSource: "Federal Reserve press release",
    isLive: true,
    state: 1,
    marketId: "mock-market-4",
    oraclePubkey: hex64(4),
    expiryHeight: 920000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(40),
    yesAssetId: hex64(41),
    noAssetId: hex64(42),
    yesReissuanceToken: hex64(43),
    noReissuanceToken: hex64(44),
    creationTxid: hex64(45),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.29,
    change24h: -0.015,
    volumeBtc: 3.1,
    liquidityBtc: 9.7,
    limitOrders: [],
  },
  {
    id: "mock-5",
    nevent: "nevent1mock5",
    question: "Will Bitcoin dominance exceed 65% this year?",
    category: "Bitcoin",
    description:
      "Resolves YES if Bitcoin market cap dominance exceeds 65% on CoinGecko at any point in 2026.",
    resolutionSource: "CoinGecko",
    isLive: true,
    state: 1,
    marketId: "mock-market-5",
    oraclePubkey: hex64(5),
    expiryHeight: 915000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(50),
    yesAssetId: hex64(51),
    noAssetId: hex64(52),
    yesReissuanceToken: hex64(53),
    noReissuanceToken: hex64(54),
    creationTxid: hex64(55),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.55,
    change24h: 0.082,
    volumeBtc: 1.8,
    liquidityBtc: 5.4,
    limitOrders: [],
  },
  {
    id: "mock-6",
    nevent: "nevent1mock6",
    question: "Will a Champions League final go to penalties in 2026?",
    category: "Sports",
    description:
      "Resolves YES if the 2025-26 UEFA Champions League final is decided by a penalty shootout.",
    resolutionSource: "UEFA official results",
    isLive: true,
    state: 1,
    marketId: "mock-market-6",
    oraclePubkey: hex64(6),
    expiryHeight: 908000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(60),
    yesAssetId: hex64(61),
    noAssetId: hex64(62),
    yesReissuanceToken: hex64(63),
    noReissuanceToken: hex64(64),
    creationTxid: hex64(65),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.22,
    change24h: 0.005,
    volumeBtc: 0.9,
    liquidityBtc: 2.1,
    limitOrders: [],
  },
  {
    id: "mock-7",
    nevent: "nevent1mock7",
    question: "Will a new Satoshi Nakamoto documentary air on Netflix in 2026?",
    category: "Culture",
    description:
      "Resolves YES if Netflix releases a documentary primarily about Satoshi Nakamoto's identity before Dec 31, 2026.",
    resolutionSource: "Netflix catalog",
    isLive: true,
    state: 1,
    marketId: "mock-market-7",
    oraclePubkey: hex64(7),
    expiryHeight: 912000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(70),
    yesAssetId: hex64(71),
    noAssetId: hex64(72),
    yesReissuanceToken: hex64(73),
    noReissuanceToken: hex64(74),
    creationTxid: hex64(75),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.15,
    change24h: -0.028,
    volumeBtc: 0.4,
    liquidityBtc: 1.3,
    limitOrders: [],
  },
  {
    id: "mock-8",
    nevent: "nevent1mock8",
    question: "Will Lightning Network capacity exceed 10,000 BTC?",
    category: "Bitcoin",
    description:
      "Resolves YES if total Lightning Network capacity exceeds 10,000 BTC at any point in 2026.",
    resolutionSource: "mempool.space Lightning explorer",
    isLive: true,
    state: 1,
    marketId: "mock-market-8",
    oraclePubkey: hex64(8),
    expiryHeight: 918000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(80),
    yesAssetId: hex64(81),
    noAssetId: hex64(82),
    yesReissuanceToken: hex64(83),
    noReissuanceToken: hex64(84),
    creationTxid: hex64(85),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.44,
    change24h: 0.061,
    volumeBtc: 1.5,
    liquidityBtc: 4.8,
    limitOrders: [],
  },
  {
    id: "mock-9",
    nevent: "nevent1mock9",
    question: "Will El Salvador's Bitcoin bonds be fully subscribed?",
    category: "Macro",
    description:
      "Resolves YES if El Salvador's Volcano Bonds reach full subscription before their offering closes.",
    resolutionSource: "El Salvador Ministry of Finance",
    isLive: true,
    state: 1,
    marketId: "mock-market-9",
    oraclePubkey: hex64(9),
    expiryHeight: 907000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(90),
    yesAssetId: hex64(91),
    noAssetId: hex64(92),
    yesReissuanceToken: hex64(93),
    noReissuanceToken: hex64(94),
    creationTxid: hex64(95),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.67,
    change24h: -0.041,
    volumeBtc: 2.0,
    liquidityBtc: 6.2,
    limitOrders: [],
  },
  {
    id: "mock-10",
    nevent: "nevent1mock10",
    question: "Will MicroStrategy hold over 500,000 BTC by year end?",
    category: "Bitcoin",
    description:
      "Resolves YES if MicroStrategy's Bitcoin holdings exceed 500,000 BTC as reported in any quarterly filing before Dec 31, 2026.",
    resolutionSource: "MicroStrategy quarterly filings (SEC EDGAR)",
    isLive: true,
    state: 1,
    marketId: "mock-market-10",
    oraclePubkey: hex64(100),
    expiryHeight: 925000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(101),
    yesAssetId: hex64(102),
    noAssetId: hex64(103),
    yesReissuanceToken: hex64(104),
    noReissuanceToken: hex64(105),
    creationTxid: hex64(106),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.81,
    change24h: 0.021,
    volumeBtc: 4.2,
    liquidityBtc: 11.5,
    limitOrders: [],
  },
  {
    id: "mock-11",
    nevent: "nevent1mock11",
    question: "Will the SEC approve a spot Ethereum ETF staking amendment?",
    category: "Macro",
    description:
      "Resolves YES if the SEC approves an amendment allowing staking within any spot Ethereum ETF before Dec 31, 2026.",
    resolutionSource: "SEC filing / Federal Register",
    isLive: true,
    state: 1,
    marketId: "mock-market-11",
    oraclePubkey: hex64(110),
    expiryHeight: 930000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(111),
    yesAssetId: hex64(112),
    noAssetId: hex64(113),
    yesReissuanceToken: hex64(114),
    noReissuanceToken: hex64(115),
    creationTxid: hex64(116),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.45,
    change24h: -0.033,
    volumeBtc: 3.6,
    liquidityBtc: 7.8,
    limitOrders: [],
  },
  {
    id: "mock-12",
    nevent: "nevent1mock12",
    question:
      "Will a nation-state besides El Salvador adopt BTC as legal tender?",
    category: "Politics",
    description:
      "Resolves YES if any sovereign nation besides El Salvador enacts legislation making Bitcoin legal tender before Dec 31, 2026.",
    resolutionSource: "Official government gazette of adopting nation",
    isLive: true,
    state: 1,
    marketId: "mock-market-12",
    oraclePubkey: hex64(120),
    expiryHeight: 935000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(121),
    yesAssetId: hex64(122),
    noAssetId: hex64(123),
    yesReissuanceToken: hex64(124),
    noReissuanceToken: hex64(125),
    creationTxid: hex64(126),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.12,
    change24h: 0.012,
    volumeBtc: 0.85,
    liquidityBtc: 2.4,
    limitOrders: [],
  },
  {
    id: "mock-13",
    nevent: "nevent1mock13",
    question: "Will the 2026 FIFA World Cup final have over 2.5 goals?",
    category: "Sports",
    description:
      "Resolves YES if the 2026 FIFA World Cup final match ends with a combined total of 3 or more goals (excluding penalties).",
    resolutionSource: "FIFA official match report",
    isLive: true,
    state: 1,
    marketId: "mock-market-13",
    oraclePubkey: hex64(130),
    expiryHeight: 940000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(131),
    yesAssetId: hex64(132),
    noAssetId: hex64(133),
    yesReissuanceToken: hex64(134),
    noReissuanceToken: hex64(135),
    creationTxid: hex64(136),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.58,
    change24h: 0.009,
    volumeBtc: 1.1,
    liquidityBtc: 3.2,
    limitOrders: [],
  },
  {
    id: "mock-14",
    nevent: "nevent1mock14",
    question: "Will a Category 5 typhoon hit Japan before November 2026?",
    category: "Weather",
    description:
      "Resolves YES if a Category 5 super typhoon makes landfall in Japan before Nov 1, 2026.",
    resolutionSource: "Japan Meteorological Agency",
    isLive: true,
    state: 1,
    marketId: "mock-market-14",
    oraclePubkey: hex64(140),
    expiryHeight: 928000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(141),
    yesAssetId: hex64(142),
    noAssetId: hex64(143),
    yesReissuanceToken: hex64(144),
    noReissuanceToken: hex64(145),
    creationTxid: hex64(146),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.34,
    change24h: -0.007,
    volumeBtc: 0.7,
    liquidityBtc: 1.9,
    limitOrders: [],
  },
  {
    id: "mock-15",
    nevent: "nevent1mock15",
    question: "Will Nostr reach 10 million monthly active users in 2026?",
    category: "Culture",
    description:
      "Resolves YES if Nostr protocol reaches 10 million monthly active users on any tracking service before Dec 31, 2026.",
    resolutionSource: "Nostr.com stats page",
    isLive: true,
    state: 1,
    marketId: "mock-market-15",
    oraclePubkey: hex64(150),
    expiryHeight: 945000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(151),
    yesAssetId: hex64(152),
    noAssetId: hex64(153),
    yesReissuanceToken: hex64(154),
    noReissuanceToken: hex64(155),
    creationTxid: hex64(156),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.18,
    change24h: 0.045,
    volumeBtc: 0.55,
    liquidityBtc: 1.6,
    limitOrders: [],
  },
  {
    id: "mock-16",
    nevent: "nevent1mock16",
    question: "Will Bitcoin mining difficulty exceed 120T before Q3 2026?",
    category: "Bitcoin",
    description:
      "Resolves YES if Bitcoin network mining difficulty exceeds 120 trillion before Jul 1, 2026.",
    resolutionSource: "mempool.space mining dashboard",
    isLive: true,
    state: 1,
    marketId: "mock-market-16",
    oraclePubkey: hex64(160),
    expiryHeight: 902000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(161),
    yesAssetId: hex64(162),
    noAssetId: hex64(163),
    yesReissuanceToken: hex64(164),
    noReissuanceToken: hex64(165),
    creationTxid: hex64(166),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.63,
    change24h: 0.014,
    volumeBtc: 1.9,
    liquidityBtc: 5.1,
    limitOrders: [],
  },
  {
    id: "mock-17",
    nevent: "nevent1mock17",
    question: "Will the US 10-year Treasury yield drop below 3.5%?",
    category: "Macro",
    description:
      "Resolves YES if the US 10-year Treasury yield closes below 3.50% on any trading day before Dec 31, 2026.",
    resolutionSource: "US Treasury Department / FRED",
    isLive: true,
    state: 1,
    marketId: "mock-market-17",
    oraclePubkey: hex64(170),
    expiryHeight: 948000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(171),
    yesAssetId: hex64(172),
    noAssetId: hex64(173),
    yesReissuanceToken: hex64(174),
    noReissuanceToken: hex64(175),
    creationTxid: hex64(176),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.24,
    change24h: -0.021,
    volumeBtc: 2.7,
    liquidityBtc: 8.4,
    limitOrders: [],
  },
  {
    id: "mock-18",
    nevent: "nevent1mock18",
    question: "Will a European country ban proof-of-work mining in 2026?",
    category: "Politics",
    description:
      "Resolves YES if any EU member state enacts a ban on proof-of-work cryptocurrency mining before Dec 31, 2026.",
    resolutionSource: "Official Gazette of the legislating country",
    isLive: true,
    state: 1,
    marketId: "mock-market-18",
    oraclePubkey: hex64(180),
    expiryHeight: 950000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(181),
    yesAssetId: hex64(182),
    noAssetId: hex64(183),
    yesReissuanceToken: hex64(184),
    noReissuanceToken: hex64(185),
    creationTxid: hex64(186),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.09,
    change24h: -0.004,
    volumeBtc: 0.35,
    liquidityBtc: 0.95,
    limitOrders: [],
  },
  {
    id: "mock-19",
    nevent: "nevent1mock19",
    question:
      "Will the Bitcoin mempool clear to under 1 sat/vB for a full week?",
    category: "Bitcoin",
    description:
      "Resolves YES if the Bitcoin mempool recommended fee stays at or below 1 sat/vB for 7 consecutive days in 2026.",
    resolutionSource: "mempool.space fee estimates",
    isLive: true,
    state: 1,
    marketId: "mock-market-19",
    oraclePubkey: hex64(190),
    expiryHeight: 938000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(191),
    yesAssetId: hex64(192),
    noAssetId: hex64(193),
    yesReissuanceToken: hex64(194),
    noReissuanceToken: hex64(195),
    creationTxid: hex64(196),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.41,
    change24h: 0.038,
    volumeBtc: 1.3,
    liquidityBtc: 3.9,
    limitOrders: [],
  },
  {
    id: "mock-20",
    nevent: "nevent1mock20",
    question: "Will a major AI lab accept Bitcoin payments by end of 2026?",
    category: "Culture",
    description:
      "Resolves YES if any of the top 5 AI labs (by compute) publicly accepts Bitcoin as a payment method before Dec 31, 2026.",
    resolutionSource: "Official announcement from the AI lab",
    isLive: true,
    state: 1,
    marketId: "mock-market-20",
    oraclePubkey: hex64(200),
    expiryHeight: 942000,
    currentHeight: 885000,
    cptSats: 100,
    collateralAssetId: hex64(201),
    yesAssetId: hex64(202),
    noAssetId: hex64(203),
    yesReissuanceToken: hex64(204),
    noReissuanceToken: hex64(205),
    creationTxid: hex64(206),
    anchor: null,
    collateralUtxos: [],
    nostrEventJson: null,
    anchor: null,
    yesPrice: 0.52,
    change24h: 0.073,
    volumeBtc: 2.15,
    liquidityBtc: 6.0,
    limitOrders: [],
  },
];
